version: '3'

services:

  #------------------------------------
  # couchdb container
  #------------------------------------
  couch:
    build: 
      dockerfile: ./_datastore/Dockerfile
      context: .
    ports:
      - 5984:5984

  #------------------------------------
  # couchdb setup container: curl some
  # data files into the database
  #------------------------------------
  couch-setup:
    build:
      dockerfile: ./_helper/Dockerfile
      context: .
    volumes:
      - ./_helper:/app
    depends_on:
      - couch

  #----------------------------
  # flask service container
  #----------------------------
  flask:
    build:
      dockerfile: ./_service/Dockerfile
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment: 
      FLASK_ENV: development
      FLASK_APP: service.py
    depends_on:
      - couch-setup